#Requires -Version 5.1
<#
.SYNOPSIS
    Writes a certreq INF for the IIS machine certificate (Subject + SAN = server FQDN).

.DESCRIPTION
    2026 REPRODUCIBILITY EXTENSION. The original lab generated the request with certreq;
    its INF file was not preserved, so this is a reconstruction of the documented outcome
    (CN=server.irb.local, SAN DNS=server.irb.local), not a copy of the original file.

    This script only writes a text file. It prints the certreq commands to run next.
    The key pair is generated by certreq inside the LocalMachine store and is marked
    non-exportable; no key material is ever written to disk by this repository.

    The template name is a 2026 choice (the built-in "WebServer" template). The original
    lab report does not record which template was used.

.EXAMPLE
    .\New-ServerCertificateRequest.ps1 -OutFile C:\pki\server.inf
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [string] $ServerFqdn = 'server.irb.local',
    [string] $Template = 'WebServer',
    [ValidateSet(2048, 3072, 4096)] [int] $KeyLength = 2048,
    [string] $OutFile = (Join-Path (Get-Location) 'server.inf'),
    [string] $CaConfig = "$env:COMPUTERNAME\IRB-ADCS-RootCA"
)

if ($ServerFqdn -notmatch '^(?=.{1,253}$)([a-zA-Z0-9-]{1,63}\.)+[a-zA-Z0-9-]{1,63}$') {
    throw "ServerFqdn '$ServerFqdn' is not a valid DNS name."
}

$inf = @"
[Version]
Signature = "`$Windows NT`$"

[NewRequest]
Subject = "CN=$ServerFqdn"
KeyLength = $KeyLength
KeyAlgorithm = RSA
HashAlgorithm = SHA256
MachineKeySet = TRUE
Exportable = FALSE
KeySpec = 1
KeyUsage = 0xA0
ProviderName = "Microsoft RSA SChannel Cryptographic Provider"
RequestType = PKCS10

[EnhancedKeyUsageExtension]
OID = 1.3.6.1.5.5.7.3.1

[Extensions]
2.5.29.17 = "{text}"
_continue_ = "dns=$ServerFqdn"

[RequestAttributes]
CertificateTemplate = $Template
"@

if ($PSCmdlet.ShouldProcess($OutFile, 'Write certreq INF')) {
    Set-Content -LiteralPath $OutFile -Value $inf -Encoding ASCII
    $base = [System.IO.Path]::ChangeExtension($OutFile, $null).TrimEnd('.')
    Write-Output "Wrote $OutFile"
    Write-Output ''
    Write-Output 'Next steps (run elevated on the server):'
    Write-Output "  certreq -new    `"$OutFile`" `"$base.req`""
    Write-Output "  certreq -submit -config `"$CaConfig`" `"$base.req`" `"$base.cer`""
    Write-Output "  certreq -accept `"$base.cer`""
}
